### ISSUE TITLE
Ruby is less talked about

### ISSUE THREAD

**Issue by sheosi** [mjhea0/python-ruby#6]
Whilee you talked a lot about Python, you left some things about Ruby:
1. You talked about Python's simplicty, and you left Ruby's explicit desire of making the programmer happy
2. Also you left the principle of least astonishment something very important in Ruby
3. Ruby has an advantage over python and it is adding methods to existing classes
4. I don't think the if part it's ruby code that follows ruby's way, as ruby's way it's more about multiple functions for the same (with different names) and using classes as much as possible, that seems to be just unreadable code, if it makes it's programmer happy then it may be (but only for himself I think), but otherwise it is not.
Just wanting to clarify, as Python part feeled much more developed than Ruby's :) .

**Comment by mjhea0** [comment]
@sheosi - very good points. Did you want to update the post? I'd really like to get all this added.

1. This could be a positive or negative, depending on how you look at it. I think there's a spectrum between one best way of doing something (Python) vs a million ways of doing something (Perl). Ruby falls somewhere on that spectrum, probably closer to Perl. On the one hand, it's good that Ruby does have more options. On the other, it can confuse beginners.
1. The Principle of Least Astonishment is pretty controversial. I know that the language is build on it, and I am trying to be more objective - but this is really open to debate. In fact, I'd say that Python follows the principle better, especially beginner coders working with Python 3. http://lucumr.pocoo.org/2011/7/9/python-and-pola/. That said, I'd still like to add it.
1. Good point
1. Feel free to update.

**Comment by sheosi** [comment]
Pull request added.

**Comment by mjhea0** [comment]
Thanks!
