### ISSUE TITLE
same function different name

### ISSUE THREAD

**Issue by james4388** [mjhea0/python-ruby#8]
I dont understand this
```
Although you can write this code in many ways, both of these methods are true to the language.
The Ruby code demonstrates the practice of having multiple names for the same function (fib and fibonacci are the same).
```
In Python you can `def fibonaci` then `fib = fibonaci` and both fib and fibonaci point in to same function

**Comment by mjhea0** [comment]
@james4388 Sure you can do aliasing in Python, but in my experience, it's seen as a bad practice. It's much more acceptable to Rubyists. Would you agree with that?
