### ISSUE TITLE
Rubyist fib(n) with ternary operator

### ISSUE THREAD

**Issue by jaxn** [mjhea0/python-ruby#9]
As someone who writes Ruby regularly, I felt your `fib(n)` seemed awkward.

```ruby
fib(n)
  n < 2 ? n : fib(n-1) + fib(n-2)
end
alias :fibonacci :fib
```

I think that example is true to the ruby style as well as true to your argument.

**Comment by mjhea0** [comment]
Looks good. Want to issue a PR?
